const SUBMIT_BOOKING = 'SUBMIT_BOOKING';
const EDIT_BOOKING = 'EDIT_BOOKING';
const DELETE_BOOKING = 'DELETE_BOOKING';
const UPDATE_BOOKING = 'UPDATE_BOOKING';

export {
    SUBMIT_BOOKING,
    EDIT_BOOKING,
    DELETE_BOOKING,
    UPDATE_BOOKING
};